apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mysql
  labels:
    app: mysql
spec:
  capacity:
    storage: 200Mi   # Reduced from 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/mysql-data

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-mysql
  namespace: db-ns
  labels:
    app: mysql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi   # Reduced from 1Gi

